
import Head from 'next/head'
import Container from '../components/Container'

export default function index() {
  return (
    <div>
      <Head>
        <title>Win Aung</title>
        <meta name="description" content="Generated by create next app width=device-width, user-scalable=no"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container/>
    </div>
  )
}
