
import Head from 'next/head'
import Container from '../components/Container'

export default function index() {
  return (
    <div>
      <Head>
        <title>Win Aung</title>
        <meta name="description" content="Generated by create next app width=device-width, user-scalable=no"
        />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
<link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Caveat+Brush&display=swap" rel="stylesheet"/>

      </Head>
      <Container/>
    </div>
  )
}
